// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/21/2024, 1:06:16 PM
const configMerger = require("/Users/higherthought/Documents/todo-list-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/higherthought/Documents/todo-list-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/higherthought/Documents/todo-list-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/higherthought/Documents/todo-list-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/higherthought/Documents/todo-list-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/higherthought/Documents/todo-list-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/higherthought/Documents/todo-list-nuxt/plugins/**/*.{js,ts,mjs}","/Users/higherthought/Documents/todo-list-nuxt/composables/**/*.{js,ts,mjs}","/Users/higherthought/Documents/todo-list-nuxt/utils/**/*.{js,ts,mjs}","/Users/higherthought/Documents/todo-list-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/higherthought/Documents/todo-list-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/higherthought/Documents/todo-list-nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
